def loginTemplate(full_name):
    return  '''
  <!doctype html><html><head> <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> <meta charset="utf-8"> <title>Diemo</title> <style> .invoice-box { max-width: 800px; margin: auto; padding: 30px; border: 1px solid #eee; box-shadow: 0 0 10px rgba(0, 0, 0, .15); font-size: 16px; line-height: 24px; font-family: 'Helvetica Neue', 'Helvetica', 'Helvetica', 'Arial', 'sans-serif'; color: #555; } .invoice-box table { width: 100%; line-height: inherit; text-align: left; } .invoice-box table td { padding: 5px; vertical-align: top; } .invoice-box table tr.top table td { padding-bottom: 20px; } .invoice-box table tr.top table td.title { font-size: 45px; line-height: 45px; color: #333; } .invoice-box table tr.information table td { padding-bottom: 40px; } @media only screen and (max-width: 600px) { .invoice-box table tr.top table td { width: 100%; display: block; text-align: center; } .invoice-box table tr.information table td { width: 100%; display: block; text-align: center; } } .footer { color: white; background: #004E8D; border-bottom: 1px solid #FBB03B; font-weight: bold; } .right { text-align: right; } .center { text-align: center; }
/** SOCIAL ICONS **/ .fa { padding: 10px; font-size: 30px; width: 30px; text-align: center; text-decoration: none; border-radius: 50%; vertical-align: middle; } .fa:hover { opacity: 0.7; }
.button { background-color: #004E8D; /* Green */ border: none; color: white !important; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; border-radius: 8px; margin: 10px; } a:link, a:visited, a:hover, a:active { color: white; }
.footer td {
text-align: center;
background-color: #42629A;
}
</style></head><body> <div class="invoice-box"> <table cellpadding="0" cellspacing="0"> <tr class="top"> <td colspan="3"> <table> <tr> <td class="title"> <img src="https://lh3.googleusercontent.com/proxy/pD_uY29CwhBzWyEBwC9y__fZgRoOGxSDNFDYQ2qd5pT9RQMXLSg_Ix7I1gGxhtIMCBLwdYWI_C4OPvVMqSUJK9S3YJIk2ZpxxBC1i4xVEJvFWGPLW8s" style="width:100%; max-width:200px;"> </td>  <td class="text-center"> <b>Correo de bienvenida </b></td> </tr> </table> </td> </tr> <tr class="information"> <td colspan="3"> <table> </table> </td> </tr> <tr> <td style="text-indent: 1cm"> <p>Estimado <b>'''+full_name+'''</b>, bienvenido. </td> </tr> <tr > <td colspan="0"> <table id="footer"> <tr class="footer "> <td >Copyright 2020 C.A.</td> </tr> </table> </td> </tr> </table> </div></body></html>'''



def signupTemplate(full_name):
    return '''
  <!doctype html><html><head> <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> <meta charset="utf-8"> <title>Diemo</title> <style> .invoice-box { max-width: 800px; margin: auto; padding: 30px; border: 1px solid #eee; box-shadow: 0 0 10px rgba(0, 0, 0, .15); font-size: 16px; line-height: 24px; font-family: 'Helvetica Neue', 'Helvetica', 'Helvetica', 'Arial', 'sans-serif'; color: #555; } .invoice-box table { width: 100%; line-height: inherit; text-align: left; } .invoice-box table td { padding: 5px; vertical-align: top; } .invoice-box table tr.top table td { padding-bottom: 20px; } .invoice-box table tr.top table td.title { font-size: 45px; line-height: 45px; color: #333; } .invoice-box table tr.information table td { padding-bottom: 40px; } @media only screen and (max-width: 600px) { .invoice-box table tr.top table td { width: 100%; display: block; text-align: center; } .invoice-box table tr.information table td { width: 100%; display: block; text-align: center; } } .footer { color: white; background: #004E8D; border-bottom: 1px solid #FBB03B; font-weight: bold; } .right { text-align: right; } .center { text-align: center; }
/** SOCIAL ICONS **/ .fa { padding: 10px; font-size: 30px; width: 30px; text-align: center; text-decoration: none; border-radius: 50%; vertical-align: middle; } .fa:hover { opacity: 0.7; }
.button { background-color: #004E8D; /* Green */ border: none; color: white !important; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; border-radius: 8px; margin: 10px; } a:link, a:visited, a:hover, a:active { color: white; }
.footer td {
text-align: center;
background-color: #42629A;
}
</style></head><body> <div class="invoice-box"> <table cellpadding="0" cellspacing="0"> <tr class="top"> <td colspan="3"> <table> <tr> <td class="title"> <img src="https://lh3.googleusercontent.com/proxy/pD_uY29CwhBzWyEBwC9y__fZgRoOGxSDNFDYQ2qd5pT9RQMXLSg_Ix7I1gGxhtIMCBLwdYWI_C4OPvVMqSUJK9S3YJIk2ZpxxBC1i4xVEJvFWGPLW8s" style="width:100%; max-width:200px;"> </td>  <td class="text-center"> <b>Correo de bienvenida </b></td> </tr> </table> </td> </tr> <tr class="information"> <td colspan="3"> <table> </table> </td> </tr> <tr> <td style="text-indent: 1cm"> <p>Estimado <b>'''+full_name+'''</b>, bienvenido. </td> </tr> <tr > <td colspan="0"> <table id="footer"> <tr class="footer "> <td >Copyright 2020 C.A.</td> </tr> </table> </td> </tr> </table> </div></body></html>'''


def forgotPwTemplate(code):
    return '''
     <!doctype html><html><head> <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script> <meta charset="utf-8"> <title>Diemo</title> <style> .invoice-box { max-width: 800px; margin: auto; padding: 30px; border: 1px solid #eee; box-shadow: 0 0 10px rgba(0, 0, 0, .15); font-size: 16px; line-height: 24px; font-family: 'Helvetica Neue', 'Helvetica', 'Helvetica', 'Arial', 'sans-serif'; color: #555; } .invoice-box table { width: 100%; line-height: inherit; text-align: left; } .invoice-box table td { padding: 5px; vertical-align: top; } .invoice-box table tr.top table td { padding-bottom: 20px; } .invoice-box table tr.top table td.title { font-size: 45px; line-height: 45px; color: #333; } .invoice-box table tr.information table td { padding-bottom: 40px; } @media only screen and (max-width: 600px) { .invoice-box table tr.top table td { width: 100%; display: block; text-align: center; } .invoice-box table tr.information table td { width: 100%; display: block; text-align: center; } } .footer { color: white; background: #004E8D; border-bottom: 1px solid #FBB03B; font-weight: bold; } .right { text-align: right; } .center { text-align: center; }
/** SOCIAL ICONS **/ .fa { padding: 10px; font-size: 30px; width: 30px; text-align: center; text-decoration: none; border-radius: 50%; vertical-align: middle; } .fa:hover { opacity: 0.7; }
.button { background-color: #004E8D; /* Green */ border: none; color: white !important; padding: 15px 32px; text-align: center; text-decoration: none; display: inline-block; font-size: 16px; border-radius: 8px; margin: 10px; } a:link, a:visited, a:hover, a:active { color: white; }
.footer td {
text-align: center;
background-color: #42629A;
}
</style></head><body> <div class="invoice-box"> <table cellpadding="0" cellspacing="0"> <tr class="top"> <td colspan="3"> <table> <tr> <td class="title"> <img src="https://lh3.googleusercontent.com/proxy/pD_uY29CwhBzWyEBwC9y__fZgRoOGxSDNFDYQ2qd5pT9RQMXLSg_Ix7I1gGxhtIMCBLwdYWI_C4OPvVMqSUJK9S3YJIk2ZpxxBC1i4xVEJvFWGPLW8s" style="width:100%; max-width:200px;"> </td>  <td class="text-center"> <b>Correo de recuperación de contraseña. </b></td> </tr> </table> </td> </tr> <tr class="information"> <td colspan="3"> <table> </table> </td> </tr> <tr> <td style="text-indent: 1cm"> <p>Código de recuperación: <b>''+data['code']+''</b>. </td> </tr> <tr > <td colspan="0"> <table id="footer"> <tr class="footer "> <td >Copyright 2020 C.A.</td> </tr> </table> </td> </tr> </table> </div></body></html>'''